### ISSUE TITLE
Zip File index.html not working

### ISSUE THREAD

**Issue by ldblecher** [terrymun/Fluidbox#130]
After downloading the zip file of this github project, I opened up the index.html file to test it out, and whenever I click on an image, it just brings up the image in a separate screen. No fluidbox effects or anything. I tried implementing fluidbox on my own project, and the same thing happens. I didn't alter the files in the zip at all after downloading them, so I am curious as to why the fluidbox effect is not working. It would be great if you could provide some assistance. Thanks!

Edit: Noticed that there are multiple console issues because some files can't be found (below). How can I get past this to implement the fluidbox effect on my own project?

<img width="1234" alt="screen shot 2015-08-05 at 10 21 04 pm" src="https://cloud.githubusercontent.com/assets/11952092/9102447/557f049e-3bc0-11e5-8757-6104c17b93a0.png">

**Comment by terrymun** [comment]
That is because the resources are loaded with a protocol agnostic url, i.e. `//path/to/file`, instead of `http://path/to/file` or `https://path/to/file`. A quick fix would be to append `https:` to all these URLs. You can see from your error messages that your browser is attempting to load the files from a local directory, which of course do not exist.
