### ISSUE TITLE
thumbnails aren't scaling to full size

### ISSUE THREAD

**Issue by go-bears** [terrymun/Fluidbox#132]
I'm trying to implement Fluidbox on my Google Summer of Code  2015 project for WebLogo, a bioinformatics visualization tool.  WebLogo is popular with biologists and has over 4000 citations. I'm refactoring the front end to be responsive to mobile devices, and I'm using fluidbox to display the example sequence logo images.  I had used fluidbox for a related small scale project and the images had zoomed to full size, and now the images don't scale to their full size. The images do scale up slightly, but scaling to it's full size is important to biologists who need to see the tic marks and intervals on example images.   I tried changing the viewport size. and after reading the docs. I think the issue is in the feature you introduced in version 1.3.4.  , where you limit enlargement for lower resolution pictures.  

Fluidbox worked perfectly with these images in fall 2014, and scaled to their full size. How would I turn off this feature in my current implementation? Or what would be the minimum resolution of images that I need to use in order to scale to full screen size?  This issue is time sensitive b/c GSOC 2015 has pencils down on Friday Aug, 21,  I love the tool, and would be proud to list it as an example of fluidbox in the wild once I get it working. Thank you for any input!

**Comment by terrymun** [comment]
The image scaling in Fluidbox, by default, attempts to fill the viewport in its entirety (or by a certain fraction as dictated by the settings). However, if it detects an image not having sufficient dimensions to fill the viewport along either axis, it will fall back to the largest natural dimensions of the image.

The issue you are seeing is likely due to insufficient image resolution. This feature cannot be turned off for obvious reasons, but if you want to you can simply remove the conditional statements in [lines 140](https://github.com/terrymun/Fluidbox/blob/master/jquery.fluidbox.js#L140) and [156](https://github.com/terrymun/Fluidbox/blob/master/jquery.fluidbox.js#L156) respectively in the source code yourself.

p/s: I believe you do not fully comprehend how most open source projects, made by individual developers out of their own free time, work. We do not have all the time to devote to fixing an issue within a certain timeframe. I find that demanding an author to fix an issue before a deadline is against the spirit of it, let alone preposterously self-entitled.
