### ISSUE TITLE
max-width

### ISSUE THREAD

**Issue by davmuse** [terrymun/Fluidbox#139]
In addition to the `viewportFill` options, would it be possible to add a sort of `max-width` option for the target image ? (It could be interesting to target a high resolution picture (@2x) for retina display)
Thanks

**Comment by terrymun** [comment]
This is a very interesting (and poignant) question. I have given it some though, and the issue seems to be two-fold: how should we deal with scaling? Should we:

1. Allow users to restrict the scaling of the ghost element, to ensure that pixel densities are respected (hence keeping the images crisp)
2. Allow users to specify high resolution alternatives for different screen resolutions?

It isn't as straightforward as I wanted it to be, because there are more than just the old-school 2x pixel density we are talking about. Pixel density has increased (in number and in varieties) over the past few years with the advent of better and cheaper screen manufacturing technology, so if this feature is to be added, it has to account for (1) multiple pixel density values and/or (2) multiple versions of retina-ready images.

I can think of:
1. Allowing users to manually specify the scaling of the image, by exposing a public method, allowing users to dynamically determine how to rescale the CSS transform scale property based on pixel density.
2. Allowing users to manually specify the image sources by exposing another public method, which the users can then sniff for pixel densities conditionally before injected the appropriate image sources.

What do you reckon?

**Comment by davmuse** [comment]
I see the problem in a simpler way : the aim of your plug-in is not to handle retina or non-retina images ... (as you say somewhere, it has to keep simple and usable by people like me who are not jquery specialists, and that's what I appreciate ! ). Personally I use oversize images to have a better images rendering on retina display.

My suggestion is more basic : aesthetically, i prefer to control the width of the target image. For example : my website is 1000px wide, and I want the target image to be as wide, not wider. It's impossible to get that with the  `viewportFill`. 

So I'd like to have a sort of `max-width` option, to force the max-width of the target image.

And the **benefits** are 
— it would be possible (if wanted) to link a 2000px image (=@2x), that could enhance the image rendering ...
— it would be possible to have a sharp render of a small image (such as an png icon that don't need to be too wide on the screen)

(sorry for my poor english)

**Comment by davmuse** [comment]
So I tried to add this option : i added a `maxWidth` option (0 = default behavior, x = maximum width)

```javascript

var settings = $.extend(true, {
	viewportFill: 0.95,
	debounceResize: true,
	stackIndex: 1000,
	stackIndexDelta: 10,
	closeTrigger: [
		{ selector: '.fluidbox-overlay', event: 'click' },
		{ selector: 'document', event: 'keyup', keyCode: 27 }
		],
	immediateOpen: false,
	loadingEle: true,
	maxWidth: 0 			
}, opts);

```

and two test-lines : 

```javascript
if( (fHeight*$img.data().imgRatio > settings.maxWidth) && (settings.maxWidth > 0) ) { fHeight = (settings.maxWidth)/($img.data().imgRatio); }
```

```javascript
if((fWidth > settings.maxWidth) && (settings.maxWidth > 0)) { fWidth = settings.maxWidth; }  // TEST
```

**and it works as I wanted !**

this is in this part of the code 

```javascript
// Check natural dimensions
	if ( vpRatio > $img.data().imgRatio ) {
        // Check if linked image is smaller or larger than intended fill
		if($data.natHeight < $w.height()*settings.viewportFill) { fHeight = $data.natHeight; } else { fHeight = $w.height()*settings.viewportFill; }
	
    // HERE				
	if( (fHeight*$img.data().imgRatio > settings.maxWidth) && (settings.maxWidth > 0) ) { fHeight = (settings.maxWidth)/($img.data().imgRatio); } 
					 
	// Calculate how much to scale along the y-axis
	$data.imgScale = fHeight/$img.height();
	$data.imgScaleY = $data.imgScale;

	// Calcualte how much to scale along the x-axis
	$data.imgScaleX = $data.natWidth*(($img.height()*$data.imgScaleY)/$data.natHeight)/$img.width();

	} else { if($data.natWidth < $w.width()*settings.viewportFill) { fWidth = $data.natWidth; } else { fWidth = $w.width()*settings.viewportFill; }
					
	// AND HERE			
	if((fWidth > settings.maxWidth) && (settings.maxWidth > 0)) { fWidth = settings.maxWidth; }  
					
	// Calculate how much to scale along the x-axis
	$data.imgScale = fWidth/$img.width();                                      
	$data.imgScaleX = $data.imgScale;

	// Calculate how much to scale along the y-axis
	$data.imgScaleY = $data.natHeight*(($img.width()*$data.imgScaleX)/$data.natWidth)/$img.height();
				}
```

Thanks and I wish you courage for your massive code revision.

**Comment by terrymun** [comment]
The `maxWidth` and `maxHeight` options are available as of v2.x :)
