### ISSUE TITLE
OpenEnd and CloseEnd events fire on page load, not on event

### ISSUE THREAD

**Issue by monopine** [terrymun/Fluidbox#143]
The expected behavior of the custom events OpenEnd and CloseEnd is that they fire according to their description. However, in FF, Chrome and Safari, the events fire inside document.ready(), on initial page load

Example:
$('.zoom').fluidbox()
  .on('openend', console.log('openend'))
  .on('closeend', console.log('closeend'));

**Comment by terrymun** [comment]
That is strange, and unexpected indeed. Are you able to reproduce the issue on the [demo page](http://terrymun.github.io/Fluidbox/#custom-events)? When I checked the events are triggered as expected and I wasn't doing anything different. 

Otherwise, create a minimal example and I'll have a look at it.

**Comment by monopine** [comment]
http://codepen.io/monopine/pen/vNxJJp

**Comment by terrymun** [comment]
Very strange indeed. I can reproduce your issue in your codepen, but not on a local copy of Fluidbox.

**Comment by terrymun** [comment]
Tested with v2.0, the issue appears to be fixed now: https://jsfiddle.net/teddyrised/d6c4er30/
