### ISSUE TITLE
Append fluidbox in the body tag

### ISSUE THREAD

**Issue by agrass** [terrymun/Fluidbox#167]
There is a way to append directly the overlay and the fluidbox content in the body tag? I have some issues with absolute position and z-index because the fluidbox link is inside a lot of divs tags.

Thanks!

**Comment by terrymun** [comment]
There is a way, but a long stretch. The reason why the overlay is nested within each Fluidbox instance is because it has to appear between the enlarged image, and the original thumbnail. And since the enlarge image has to animate from the original thumbnail's calculated dimensions, that means it has be placed within the immediate DOM vicinity of the latter, thereby restricting the possible placement of the overlay element.

The Fluidbox link within *any* level of nesting is not an issue—I suspect the issue you have is due to relative positioning being (unnecessarily?) declared on some parent elements, resulting in breaking of the stacking context.

The only way to do it is to change fundamentally the calculations behind Fluidbox, a task that is up to an individual user to customise. I will unfortunately not be able to dedicate resources to this.
