### ISSUE TITLE
Bootstrap's container is cropping the enlarged image

### ISSUE THREAD

**Issue by kerberjg** [terrymun/Fluidbox#188]
I'm using Bootstrap's `container` class on my main content div. However, whenever I open an image using Fluidbox, the image is cropped to `container`'s `max-width`

Screenshots: http://imgur.com/a/36c8n

I'm running on:
 - Fluidbox 2.0.5
 - jQuery 1.12.0
 - Bootstrap 3.3.7

PS: Seems to be related to #12

**Comment by terrymun** [comment]
Unfortunately that is the limitations of Fluidbox: your parent has `overflow` set to `hidden`. Note that Fluidbox injects content for each image at the same DOM level where it resides, which means you cannot hide overflows—otherwise the image will be cropped.

See https://github.com/terrymun/Fluidbox#overflowing-content
