### ISSUE TITLE
It doesn't work within a container.

### ISSUE THREAD

**Issue by dpw1** [terrymun/Fluidbox#197]
This following image is within a div.container. 

![bug-1](https://user-images.githubusercontent.com/12404809/39144269-33ad5bf6-4728-11e8-953a-5b6c89411644.png)

When I click on it, it looks like this:

![bug-2](https://user-images.githubusercontent.com/12404809/39144337-5f3e818c-4728-11e8-8427-fc4b64f75bdf.png)

It is blocked by the parent. What can I do?

**Comment by terrymun** [comment]
That's because you've created a new stacking context with the parent: please read the [precautions section(https://github.com/terrymun/Fluidbox#precautions) in the readme.

Also, helps to include a code snippet (such as a link to JSfiddle) where you can actually reproduce the issue, if you want somebody else to troubleshoot your setup.

**Comment by dpw1** [comment]
Ugh. People who don't read documentations! hahaha no, but really, I'm sorry. I will provide a fiddle with this issue. Thank you for your readiness.

**Comment by dpw1** [comment]
It was just a `overflow:hidden;` that I had added on the parent and forgot about it. Thanks!

**Comment by terrymun** [comment]
@dpw1 It happens&mdash;glad to know the readme covers most bases :)
